
EXEC('DROP SCHEMA DATA_PRAXIS')



DROP TABLE DATA_PRAXIS.TIPO_DOCUMENTO 


DROP TABLE DATA_PRAXIS.SEXO 



DROP TABLE DATA_PRAXIS.HORARIO_TURNO 


DROP TABLE DATA_PRAXIS.ESTADO_CIVIL 


DROP TABLE DATA_PRAXIS.ESTADO_TURNO 

DROP TABLE DATA_PRAXIS.ROL 

DROP TABLE DATA_PRAXIS.FUNCIONALIDAD


DROP TABLE DATA_PRAXIS.PERSONA 

DROP TABLE DATA_PRAXIS.PLAN_MEDICO 


DROP TABLE DATA_PRAXIS.TIPO_ESPECIALIDAD


DROP TABLE DATA_PRAXIS.ESPECIALIDAD


DROP TABLE DATA_PRAXIS.AFILIADO 


DROP TABLE DATA_PRAXIS.PROFESIONAL 

DROP TABLE DATA_PRAXIS.PROFESIONAL_ESPECIALIDAD




--////////////////////////////////////////////////
--  /////    Section - Functions     ///////////////
--////////////////////////////////////////////////

DROP FUNCTION DATA_PRAXIS.OBTENER_ID_PERSONA


DROP FUNCTION DATA_PRAXIS.OBTENER_ID_AFILIADO
